### ISSUE TITLE
我尝试单机训练出现下面的错误 ?

### ISSUE THREAD

**Issue by zhonggaozhe** [DeepLangAI/LingoWhale-8B#4]
2023-12-04 16:49:56,456] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-12-04 16:49:56,456] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-12-04 16:49:56,456] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-12-04 16:49:56,456] [INFO] [launch.py:163:main] dist_world_size=1
[2023-12-04 16:49:56,456] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[2023-12-04 16:49:59,911] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-12-04 16:50:00,248] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-12-04 16:50:00,248] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/root/LingoWhale-8B/finetune/finetune.py", line 155, in <module>
    train()
  File "/root/LingoWhale-8B/finetune/finetune.py", line 104, in train
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 115, in __init__
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/training_args.py", line 1372, in __post_init__
    and (self.device.type != "cuda")
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/training_args.py", line 1795, in device
    return self._setup_devices
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/training_args.py", line 1735, in _setup_devices
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/accelerate/state.py", line 180, in __init__
    dist.init_distributed(dist_backend=self.backend, auto_mpi_discovery=False, **kwargs)
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 670, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 120, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 146, in init_process_group
    torch.distributed.init_process_group(backend,
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1279, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
[2023-12-04 16:50:01,472] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2117
[2023-12-04 16:50:01,472] [ERROR] [launch.py:321:sigkill_handler] ['/root/miniconda3/envs/your_env_name/bin/python', '-u', 'finetune/finetune.py', '--local_rank=0', '--report_to', 'none', '--data_path', 'finetune/data/coig_10k.json', '--model_name_or_path', 'deeplang-ai/LingoWhale-8B', '--output_dir', 'output', '--model_max_length', '2048', '--num_train_epochs', '4', '--per_device_train_batch_size', '4', '--gradient_accumulation_steps', '1', '--save_strategy', 'epoch', '--learning_rate', '2e-5', '--lr_scheduler_type', 'constant', '--adam_beta1', '0.9', '--adam_beta2', '0.98', '--adam_epsilon', '1e-8', '--max_grad_norm', '1.0', '--weight_decay', '1e-4', '--warmup_ratio', '0.0', '--logging_steps', '1', '--gradient_checkpointing', 'True', '--deepspeed', 'finetune/ds_config.json', '--bf16', 'True', '--tf32', 'True'] exits with return code = 1

**Comment by wccccp** [comment]
> 2023-12-04 16:49:56,456] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]} [2023-12-04 16:49:56,456] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0 [2023-12-04 16:49:56,456] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]}) [2023-12-04 16:49:56,456] [INFO] [launch.py:163:main] dist_world_size=1 [2023-12-04 16:49:56,456] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0 /root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/cuda/**init**.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.) return torch._C._cuda_getDeviceCount() > 0 [2023-12-04 16:49:59,911] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect) [2023-12-04 16:50:00,248] [INFO] [comm.py:637:init_distributed] cdb=None [2023-12-04 16:50:00,248] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl Traceback (most recent call last): File "/root/LingoWhale-8B/finetune/finetune.py", line 155, in train() File "/root/LingoWhale-8B/finetune/finetune.py", line 104, in train model_args, data_args, training_args = parser.parse_args_into_dataclasses() File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses obj = dtype(**inputs) File "", line 115, in **init** File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/training_args.py", line 1372, in **post_init** and (self.device.type != "cuda") File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/training_args.py", line 1795, in device return self._setup_devices File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in **get** cached = self.fget(obj) File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/transformers/training_args.py", line 1735, in _setup_devices self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout)) File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/accelerate/state.py", line 180, in **init** dist.init_distributed(dist_backend=self.backend, auto_mpi_discovery=False, **kwargs) File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 670, in init_distributed cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size) File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 120, in **init** self.init_process_group(backend, timeout, init_method, rank, world_size) File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 146, in init_process_group torch.distributed.init_process_group(backend, File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper func_return = func(*args, **kwargs) File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group default_pg, _ = _new_process_group_helper( File "/root/miniconda3/envs/your_env_name/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1279, in _new_process_group_helper backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options) RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found! [2023-12-04 16:50:01,472] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2117 [2023-12-04 16:50:01,472] [ERROR] [launch.py:321:sigkill_handler] ['/root/miniconda3/envs/your_env_name/bin/python', '-u', 'finetune/finetune.py', '--local_rank=0', '--report_to', 'none', '--data_path', 'finetune/data/coig_10k.json', '--model_name_or_path', 'deeplang-ai/LingoWhale-8B', '--output_dir', 'output', '--model_max_length', '2048', '--num_train_epochs', '4', '--per_device_train_batch_size', '4', '--gradient_accumulation_steps', '1', '--save_strategy', 'epoch', '--learning_rate', '2e-5', '--lr_scheduler_type', 'constant', '--adam_beta1', '0.9', '--adam_beta2', '0.98', '--adam_epsilon', '1e-8', '--max_grad_norm', '1.0', '--weight_decay', '1e-4', '--warmup_ratio', '0.0', '--logging_steps', '1', '--gradient_checkpointing', 'True', '--deepspeed', 'finetune/ds_config.json', '--bf16', 'True', '--tf32', 'True'] exits with return code = 1

是否安装了正确的torch cuda版本？
